import {
	Box,
	Button,
	Center,
	Container,
	Flex,
	Grid,
	GridItem,
	Heading,
	Icon,
	Link,
	SimpleGrid,
	Stack,
	Text,
} from '@chakra-ui/react';
import {
	MdPriceCheck,
	MdOutlineSettingsSuggest,
	MdOutlineThumbUpOffAlt,
} from 'react-icons/md';
import { SkipNavContent } from '@chakra-ui/skip-nav';
import Head from 'next/head';
import { default as NextLink } from 'next/link';
import { BsGithub } from 'react-icons/bs';

export default function Home() {
	return (
		<>
			<Head>
				<title>DZ PC Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				{/* header section */}
				<Center
					display={'flex'}
					flexDirection={'column'}
					w="100%"
					h="calc(100vh - 2rem)"
					paddingBlock="3rem"
					bgColor="neon.blue"
				>
					<Heading fontSize="6xl" textAlign="center" data-testid="hero_text">
						Next.js product order apps
					</Heading>
					<Text mt={6} w={'md'}>
						Simple Next.js app that have member and admin role which for changes
						the order status with PayPal sandbox integration.
					</Text>
					<Link
						as={NextLink}
						href={'https://github.com/samudriawan/pc-company-next'}
						aria-label="Github repo"
						isExternal
						mt={6}
					>
						<Button leftIcon={<BsGithub />} variant="solid">
							Github
						</Button>
					</Link>
				</Center>

				{/* Product collection section */}
				<SkipNavContent />
				<Container
					maxW={{ sm: 'lg', md: '2xl', lg: '4xl', xl: '5xl' }}
					paddingTop="10rem"
					paddingBottom="3rem"
				>
					<Heading textAlign="center" data-testid="product_heading">
						Prebuilt PC Collection
					</Heading>
					<SimpleGrid
						columns={1}
						spacing="1rem"
						marginTop="2rem"
						placeItems={'center'}
					>
						<Link as={NextLink} href={'/product'}>
							<Button
								maxW="100%"
								bg="neon.blue"
								paddingBlock="1.4rem"
								my={6}
								transition="transform 200ms ease"
								fontSize="1.1rem"
								_hover={{ transform: 'scale(1.02)' }}
							>
								Browse Product
							</Button>
						</Link>
					</SimpleGrid>

					{/* why choose prebuild section */}
					<Stack
						border="1px"
						rounded="md"
						paddingInline="3"
						paddingBlock="5"
						marginTop="8rem"
						gap="3"
						data-testid="why_section"
					>
						<Box>
							<Heading>Kenapa pilih Prebuild?</Heading>
							<Text>
								PCs ini dirakit dan dipilih berdasarkan budget serta memenuhi
								semua kebutuhan kelas mid-range.
							</Text>
						</Box>
						<Stack direction={{ base: 'column', lg: 'row' }}>
							<Flex gap="1rem" flex="1 0">
								<Icon as={MdPriceCheck} boxSize="5rem" />
								<Box>
									<Heading>Harga</Heading>
									<Text>
										Hemat dari segi biaya rakit sendiri dan pengeluaran jika
										membeli peripheral secara terpisah.
									</Text>
								</Box>
							</Flex>
							<Flex gap="1rem" flex="1 0">
								<Icon as={MdOutlineThumbUpOffAlt} boxSize="5rem" />
								<Box>
									<Heading>Kualitas</Heading>
									<Text>
										Dapatkan kualitas yang tinggi sama seperti custom PC.
									</Text>
								</Box>
							</Flex>
							<Flex gap="1rem" flex="1 0">
								<Icon as={MdOutlineSettingsSuggest} boxSize="5rem" />
								<Box>
									<Heading>Nyaman</Heading>
									<Text>
										Dirakit dan setel serta optimalisasi dengan pilihan yang
										sederhana.
									</Text>
								</Box>
							</Flex>
						</Stack>
					</Stack>

					{/* faq section */}
					<Box marginTop="8rem" data-testid="faq_section">
						<Center marginBlock="2rem">
							<Heading>Prebuild PC FAQ</Heading>
						</Center>
						<Grid
							w="100%"
							templateColumns={{ md: '1fr', lg: 'repeat(2, 1fr)' }}
							gap="1rem"
						>
							<GridItem
								maxW="100%"
								bg="neon.blue"
								p="2rem"
								rounded="md"
								overflow="hidden"
							>
								<Heading marginBottom="1rem">
									Lorem ipsum dolor sit amet consectetur adipisicing elit.
									Recusandae, atque?
								</Heading>
								<Text>
									Lorem ipsum dolor, sit amet consectetur adipisicing elit. A
									eligendi dignissimos culpa exercitationem ex quasi hic nostrum
									repellat? Necessitatibus suscipit itaque non quaerat porro
									quas eligendi dignissimos eius asperiores corporis provident
									optio labore cum, rem soluta accusamus doloremque quam!
									Reprehenderit assumenda molestiae accusantium ipsum minus
									blanditiis facilis nihil, corporis cum minima sit beatae
									cupiditate consequatur officia, voluptatem, ipsam suscipit
									ipsa animi laudantium iste a laborum. Qui perferendis suscipit
									laborum ipsa autem vel itaque, velit excepturi amet facere
									aspernatur? Eveniet voluptatem esse quis odio, eligendi vero
									dolore quidem nulla officia expedita, sequi est quas dolores
									deleniti a, veniam in quae laudantium!
								</Text>
							</GridItem>
							<GridItem
								maxW="100%"
								bg="neon.blue"
								p="2rem"
								rounded="md"
								overflow="hidden"
							>
								<Heading marginBottom="1rem">
									Lorem ipsum dolor sit amet consectetur adipisicing elit.
									Recusandae, atque?
								</Heading>
								<Text>
									Lorem ipsum dolor, sit amet consectetur adipisicing elit. A
									eligendi dignissimos culpa exercitationem ex quasi hic nostrum
									repellat? Necessitatibus suscipit itaque non quaerat porro
									quas eligendi dignissimos eius asperiores corporis provident
									optio labore cum, rem soluta accusamus doloremque quam!
									Reprehenderit assumenda molestiae accusantium ipsum minus
									blanditiis facilis nihil, corporis cum minima sit beatae
									cupiditate consequatur officia, voluptatem, ipsam suscipit
									ipsa animi laudantium iste a laborum. Qui perferendis suscipit
									laborum ipsa autem vel itaque, velit excepturi amet facere
									aspernatur? Eveniet voluptatem esse quis odio, eligendi vero
									dolore quidem nulla officia expedita, sequi est quas dolores
									deleniti a, veniam in quae laudantium!
								</Text>
							</GridItem>
							<GridItem
								maxW="100%"
								bg="neon.blue"
								p="2rem"
								rounded="md"
								overflow="hidden"
							>
								<Heading marginBottom="1rem">
									Lorem ipsum dolor sit amet consectetur adipisicing elit.
									Recusandae, atque?
								</Heading>
								<Text marginBottom="1rem">
									Lorem ipsum dolor sit amet consectetur adipisicing elit.
									Consequatur laboriosam enim dolorum explicabo. Doloremque
									molestias iure eaque suscipit voluptas magnam!
								</Text>
								<Text>
									Lorem ipsum dolor sit amet consectetur adipisicing elit.
									Fugiat repudiandae magnam excepturi quas culpa sapiente, a
									facilis magni unde aliquam error, saepe vel necessitatibus
									omnis fuga cupiditate. Voluptatem eveniet inventore, vero
									rerum itaque cum ullam debitis dignissimos. Accusamus
									perferendis corrupti facere ea ut optio, commodi et vero
									reiciendis assumenda similique.
								</Text>
							</GridItem>
							<GridItem
								maxW="100%"
								bg="neon.blue"
								p="2rem"
								rounded="md"
								overflow="hidden"
							>
								<Heading marginBottom="1rem">
									Lorem ipsum dolor sit amet consectetur adipisicing elit.
									Recusandae, atque?
								</Heading>
								<Text>
									Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa
									necessitatibus eveniet fugit commodi quae quisquam minus,
									suscipit molestiae dicta earum ut reiciendis eligendi quia qui
									consequatur. Repellendus earum ea facere, aut consequatur
									necessitatibus pariatur temporibus vero deserunt eveniet
									repudiandae quidem totam ipsa saepe suscipit itaque eius animi
									ut alias soluta?
								</Text>
							</GridItem>
						</Grid>
					</Box>
				</Container>
			</main>
		</>
	);
}
